add_item:
  target:
    entity:
      integration: shoppingheld
      domain: todo
  fields:
    item:
      required: true
      example: "Milch"
      selector:
        text:
    amount:
      required: false
      example: 2
      selector:
        number:
          min: 1
          max: 99
          mode: box
    unit:
      required: false
      example: "Packung"
      selector:
        text:
    category:
      required: false
      selector:
        select:
          translation_key: category
          options:
            - gemuese
            - cerealien
            - brot
            - kaffee
            - knabber
            - fleisch
            - konserven
            - milch
            - milchprodukte
            - tk
            - getraenke
            - haushalt
            - koerperpflege
            - katzenfutter
            - sonstiges
